### PR TITLE
Transaction Split Tests

### PR DESCRIPTION
**Pull request by Lilit0x**
Test suites for the transaction split API

### CODE REVIEW

**Comment by Lilit0x** [comment]
Hi @morukele , I saw this when I wanted to create secrets on my own fork.

rsrssrs
But with that, the actions still fail on my own fork. Also, I sent you an email regarding the meeting.
Thanks

**Comment by morukele** [comment]
Hi @Lilit0x Your hint was correct, GitHub doesn't let PRs have access to the repo secrets.

I have updated the main branch with a potential fix for this issue. With this fix, the tests are still going to fail when you make a PR, but when I re-run it, it should pass.

Could you get the latest copy of the code and open another PR?

**Comment by Lilit0x** [comment]
Okay, doing that now.

**Comment by morukele** [comment]
The test passes! So you can write all the tests and I will have a way to verify them now!

**Comment by morukele** [comment]
@Lilit0x All tests pass and now merging with the main. Thank you very much for your contribution!

**Pull request merged**
