### PR TITLE
tests: transaction split endpoints integration tests

### PR DESCRIPTION
**Pull request by Lilit0x**

### CODE REVIEW

**Comment by morukele** [comment]
@Lilit0x I wanted to inform you that I have made some changes to the `SubaccountBodyBuilder`, there was a problem with a field in this struct which gives an error when calling the API.

If you pull the latest version of the code, you will see the update.

**Comment by morukele** [comment]
@Lilit0x Tests are failing, get the latest version of the code to work with.

**Comment by Lilit0x** [comment]
> @Lilit0x Tests are failing, get the latest version of the code to work with.

Hi there.
Thanks, I will pull the code and fix the issues.

**Comment by morukele** [comment]
@Lilit0x still getting failed tests.

Did you use a valid paystack API key?

**Comment by Lilit0x** [comment]
> @Lilit0x still getting failed tests.
> 
> Did you use a valid paystack API key?

Hi there, yes, I did.

Screenshot (272)

**Comment by Lilit0x** [comment]
Or do I have to add the key to my own actions on GitHub?

**Comment by morukele** [comment]
> Or do I have to add the key to my own actions on GitHub?

I think you may have to. I have my own keys on GitHub actions, try adding to your actions, then let me know so I can run the tests to check.

**Comment by Lilit0x** [comment]
> > Or do I have to add the key to my own actions on GitHub?
> 
> I think you may have to. I have my own keys on GitHub actions, try adding to your actions, then let me know so I can run the tests to check.

I have added it and the remaining env variables too

**Comment by Lilit0x** [comment]
I ran the tests on my own fork, and they failed too. I'll try to figure out the issue and get back to you tomorrow. 
If I am not able to fix it by then, I don't know if you'll be willing to get on a 15 to 30 minutes call to sort it out.

**Comment by morukele** [comment]
It is strange that all tests pass on your local machine but not on GitHub.

No problem at all, let me know tomorrow evening and we can get on a google-meet if necessary.

**Pull request closed without merging**
